#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
sub_service:
  hosts: HZN-WEB
  name: horizon
  service: horizon
  monitoring:
    enabled: true
    external_name: web-ui
    logging_dir: /var/log/horizon
  logging_options:
    - files:
      - /var/log/horizon/horizon_access.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - maxsize 100M
      - rotate 7
      - compress
      - missingok
      - copytruncate
      - create 640 horizon horizon
    - files:
      - /var/log/horizon/horizon_error.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - maxsize 300M
      - rotate 7
      - compress
      - missingok
      - copytruncate
      - create 640 horizon horizon
    - files:
      - /var/log/horizon/horizon-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - maxsize 400M
      - rotate 5
      - compress
      - missingok
      - copytruncate
      - create 640 horizon horizon
    - files:
      - /var/log/horizon/management/management.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - maxsize 45M
      - rotate 7
      - compress
      - missingok
      - copytruncate
      - create 640 horizon-venv horizon
    - files:
      - /var/log/horizon/management/management-json.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - maxsize 45M
      - rotate 7
      - compress
      - missingok
      - copytruncate
      - create 640 horizon-venv horizon
