#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
sub_service:
  hosts: SWF-.*
  name: swift
  service: swift
  monitoring:
    enabled: true
    external_name: object-storage
    logging_dir: /var/log/swift
  logging_options:
    - files:
      - /var/log/swift/swift.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
#      - copytruncate   # any log with postrotate script should not have copytruncate
      - maxsize 400M
      - rotate 7
      - create 640 root adm
      - postrotate
      - "  if [ -f /var/run/rsyslogd.pid ] ; then kill -HUP $(cat /var/run/rsyslogd.pid 2> /dev/null) &> /dev/null; fi || true"
      - endscript
    - files:
      - /var/log/swift/swift-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
#      - copytruncate   # any log with postrotate script should not have copytruncate
      - maxsize 400M
      - rotate 5
      - create 640 root adm
      - postrotate
      - "  if [ -f /var/run/rsyslogd.pid ] ; then kill -HUP $(cat /var/run/rsyslogd.pid 2> /dev/null) &> /dev/null; fi || true"
      - endscript
    - files:
      - /var/log/swiftlm/uptime-mon.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
#      - copytruncate   # any log with postrotate script should not have copytruncate
      - maxsize 45M
      - rotate 7
      - create 640 root adm
      - postrotate
      - "  if [ -f /var/run/rsyslogd.pid ] ; then kill -HUP $(cat /var/run/rsyslogd.pid 2> /dev/null) &> /dev/null; fi || true"
      - endscript
    - files:
      - /var/log/swiftlm/uptime-mon-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
#      - copytruncate   # any log with postrotate script should not have copytruncate
      - maxsize 45M
      - rotate 5
      - create 640 root adm
      - postrotate
      - "  if [ -f /var/run/rsyslogd.pid ] ; then kill -HUP $(cat /var/run/rsyslogd.pid 2> /dev/null) &> /dev/null; fi || true"
      - endscript
    - files:
      - swift/swift-audit.log
      centralized_audit_logging:
        enabled: true
        format: rawjson
