#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# These are the tunable values for monasca monitoring of VMs using libvirt
---

# How often disk metrics are collected for VMs by the Monasca agent. Decreasing
# this value will increase the disk, memory, cpu and network usage of Monasca
monasca_libvirt_disk_collection_period: 600 # Ten minutes

# These flags control the metrics collected by the Monasca libvirt
# plugin. Changing them to false will reduce the number of metrics while true
# increases the number of metrics.  Turning off vm_extended_disks_check_enable
# will decrease the number of metrics collected for each mounted disk in the
# VM so can have a large effect on the total number of metrics collected
# and decrease the amount of CPU, disk space and network bandwidth required
# for Monasca
vm_cpu_check_enable: true
vm_disks_check_enable: true
vm_extended_disks_check_enable: true
vm_network_check_enable: true
vm_ping_check_enable: true

# The period of time (in seconds) in which to suspend metrics from a
# newly-created VM. This is used to prevent creating and storing
# quickly-obsolete metrics in an environment with a high amount of instance
# churn (VMs created and destroyed in rapid succession).  Setting to 0
# disables VM probation and metrics will be recorded as soon as possible
# after a VM is created.  Decreasing this value in an environment with a high
# amount of instance churn can have a large effect on the total number of
# metrics collected and increase the amount of CPU, disk space and network
# bandwidth required for Monasca. This value may need to be decreased if
# Heat Autoscaling is in use so that Heat knows that a new VM has been
# created and is handling some of the load.
monasca_libvirt_vm_probation: 300
