#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# count cassandra nodes
cassandra_node_count: "{{ groups['FND-CDB'] | length }}"
cassandra_replication_factor: "{{ [2, cassandra_node_count] | min }}"


# Retention variables
kafka_low_disk_retention: 1800000 # 30 minutes in milliseconds
vertica_retention_period: 45 # 45 day default retention

# The tuning selector is normally set by the amount of RAM in the system.
# Set this variable to override that tuning. Setting it to smaller values
# can adversely affect the operation of Monasca and the components of
# Ardana OpenStack that rely on it. Possible values are: demo, small, medium, large
# and extra_large. Only demo, small, medium and large will be chosen
# based on the amount of RAM. extra_large is only used if set by
# monasca_tuning_selector_override
monasca_tuning_selector_override:

# Must be vertica or influxdb or cassandra
database_type: "{{ 'cassandra' if ansible_os_family == 'Suse' else 'vertica' }}"

# The number of seconds between metric collections for the Monasca Agent.
# Decreasing this will increase the amount of disk, CPU and RAM used by
# the Monasca components.
# Increasing this can cause issues for the Threshold Engine evaluating
# Alarms as most Alarm Definitions have a period of 60 seconds
monasca_agent_check_frequency: 30

# monasca api implementation language
monasca_api_implementation_lang: python

# Do not make changes to monasca_possible_tunings. Use the override
# parameters below in order to set individual parameters if required
monasca_possible_tunings:
    demo:
        kafka_log_retention_hours: 1 # 1 hour default retention
        kafka_heap_opts: "-Xmx128m"
        monasca_api_java_opts: "-Xmx128m"
        monasca_api_conn_timeout: 8000
        monasca_notification_alarm_processors: 1
        monasca_notification_notification_processors: 1
        monasca_persister_java_opts: "-Xmx64m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 1
        monasca_persister_metric_batch_size: 500
        storm_nimbus_childopts: "-Xmx64m"
        storm_supervisor_childopts: "-Xmx64m"
        storm_ui_childopts: "-Xmx32m"
        storm_worker_childopts_heap: "-Xmx64m"
        storm_worker_ports: [6701]
        thresh_metric_spouts: 2
        thresh_metric_threads: 2
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 200M
            - name: tm
              maxmemorysize: ''
    small:
        kafka_log_retention_hours: 4 # 4 hour default retention
        kafka_heap_opts: "-Xmx512m"
        monasca_api_java_opts: "-Xmx256m"
        monasca_api_conn_timeout: 2000
        monasca_notification_alarm_processors: 1
        monasca_notification_notification_processors: 1
        monasca_persister_java_opts: "-Xmx128m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 200
        monasca_persister_metric_threads: 1
        monasca_persister_metric_batch_size: 500
        storm_nimbus_childopts: "-Xmx128m"
        storm_supervisor_childopts: "-Xmx128m"
        storm_ui_childopts: "-Xmx64m"
        storm_worker_childopts_heap: "-Xmx128m"
        storm_worker_ports: [6701]
        thresh_metric_spouts: 2
        thresh_metric_threads: 2
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 200M
            - name: tm
              maxmemorysize: ''
    medium:
        kafka_log_retention_hours: 4 # 4 hour default retention
        kafka_heap_opts: "-Xmx1G -Xms1G"
        monasca_api_java_opts: "-Xmx512m"
        monasca_api_conn_timeout: 2000
        monasca_notification_alarm_processors: 2
        monasca_notification_notification_processors: 2
        monasca_persister_java_opts: "-Xmx512m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 2
        monasca_persister_metric_batch_size: 5000
        storm_nimbus_childopts: "-Xmx256m"
        storm_supervisor_childopts: "-Xmx256m"
        storm_ui_childopts: "-Xmx256m"
        storm_worker_childopts_heap: "-Xmx512m"
        storm_worker_ports: [6701, 6702]
        thresh_metric_spouts: 4
        thresh_metric_threads: 4
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 3G
            - name: tm
              maxmemorysize: ''
    large:
        kafka_log_retention_hours: 4 # 4 hour default retention
        kafka_heap_opts: "-Xmx2G -Xms2G"
        monasca_api_java_opts: "-Xmx1G"
        monasca_api_conn_timeout: 2000
        monasca_notification_alarm_processors: 2
        monasca_notification_notification_processors: 2
        monasca_persister_java_opts: "-Xmx1G"
        monasca_persister_alarm_threads: 2
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 2
        monasca_persister_metric_batch_size: 10000
        thresh_metric_spouts: 8
        thresh_metric_threads: 8
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 5G
            - name: tm
              maxmemorysize: ''
        storm_nimbus_childopts: "-Xmx512m"
        storm_supervisor_childopts: "-Xmx512m"
        storm_ui_childopts: "-Xmx512m"
        storm_worker_childopts_heap: "-Xmx1280m"
        storm_worker_ports: [6701, 6702, 6703, 6704]
    extra-large:
        kafka_log_retention_hours: 4 # 4 hour default retention
        kafka_heap_opts: "-Xmx3G -Xms3G"
        monasca_api_java_opts: "-Xmx2G"
        monasca_api_conn_timeout: 2000
        monasca_notification_alarm_processors: 2
        monasca_notification_notification_processors: 2
        monasca_persister_java_opts: "-Xmx2G"
        monasca_persister_alarm_threads: 2
        monasca_persister_alarm_batch_size: 200
        monasca_persister_metric_threads: 2
        monasca_persister_metric_batch_size: 100000
        thresh_metric_spouts: 8
        thresh_metric_threads: 8
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 5G
            - name: tm
              maxmemorysize: ''
        storm_nimbus_childopts: "-Xmx512m"
        storm_supervisor_childopts: "-Xmx512m"
        storm_ui_childopts: "-Xmx512m"
        storm_worker_childopts_heap: "-Xmx1536m"
        storm_worker_ports: [6701, 6702, 6703, 6704]

# Kafka Overrides
kafka_heap_opts_override:
# Must be an integer greater than 0
kafka_log_retention_hours_override:

# API Overrides
monasca_api_java_opts_override:
monasca_api_conn_timeout_override:

# Persister Overrides
monasca_persister_java_opts_override:
monasca_persister_alarm_threads_override:
monasca_persister_alarm_batch_size_override:
monasca_persister_metric_threads_override:
monasca_persister_metric_batch_size_override:

# Vertica Overrides
vertica_resource_pools_limits_override:

# Threshold Engine Overrides
thresh_metric_spout_tasks_override:
thresh_metric_spout_threads_override:

# Notification Overrides
monasca_notification_alarm_processors_override:
monasca_notification_notification_processors_override:

# Storm Overrides
storm_nimbus_childopts_override:
storm_supervisor_childopts_override:
storm_ui_childopts_override:
storm_worker_childopts_override:
storm_worker_ports_override:
